# Model compilation options
TARGET=lsd
FUN=fun_model_jeec
FUN_EXTRA=jeec_initialisation.h jeec_aggregate.h jeec_banks.h jeec_firms_capital.h jeec_firms_financial.h jeec_firms_rd.h jeec_government.h jeec_households.h jeec_firms_production.h jeec_demand_distribution.h jeec_labour_market.h jeec_entry_exit.h jeec_checks.h jeec_save.h
SWITCH_CC=/usr/share/R/include -O3 -ggdb3
SWITCH_CC_LNK=

# System compilation options
LSDROOT=/home/italo/LSD
SRC=src
EXT=

# Libraries options
TCL_VERSION=8.6
PATH_TCL_HEADER=/usr/include/tcl$(TCL_VERSION) #path to the file tcl.h
PATH_TK_HEADER=/usr/include/tcl$(TCL_VERSION) #path to the tk.h
PATH_HEADER=.
PATH_TCL_LIB=.
PATH_TK_LIB=.
PATH_LIB=.
TCL_LIB=-ltcl$(TCL_VERSION)
TK_LIB=-ltk$(TCL_VERSION)
LIBS=-lz -lpthread

# Compiler options
CC=g++
GLOBAL_CC=-march=native -std=gnu++14 -w
SSWITCH_CC=-fnon-call-exceptions -O3
LSDROOT=/home/italo/LSD

# Body of makefile (from src/makefile_base.txt)
# specify where are the sources of LSD
SRC_DIR=$(LSDROOT)/$(SRC)/

# location of tcl/tk and other headers
INCLUDE=-I$(PATH_TCL_HEADER) -I$(PATH_TK_HEADER) -I$(PATH_HEADER) -I$(LSDROOT)/$(SRC)

# link executable
$(TARGET)$(EXT): $(FUN).o $(SRC_DIR)main.o $(SRC_DIR)lsdmain.o \
$(SRC_DIR)analysis.o $(SRC_DIR)debug.o $(SRC_DIR)draw.o $(SRC_DIR)edit.o \
$(SRC_DIR)edit_dat.o $(SRC_DIR)file.o $(SRC_DIR)interf.o $(SRC_DIR)nets.o \
$(SRC_DIR)object.o $(SRC_DIR)report.o $(SRC_DIR)runtime.o $(SRC_DIR)set_all.o \
$(SRC_DIR)show_eq.o $(SRC_DIR)util.o $(SRC_DIR)variab.o
	$(CC) $(GLOBAL_CC) $(SWITCH_CC) $(FUN).o $(SRC_DIR)main.o $(SRC_DIR)lsdmain.o \
	$(SRC_DIR)analysis.o $(SRC_DIR)debug.o $(SRC_DIR)draw.o $(SRC_DIR)edit.o \
	$(SRC_DIR)edit_dat.o $(SRC_DIR)file.o $(SRC_DIR)interf.o $(SRC_DIR)nets.o \
	$(SRC_DIR)object.o $(SRC_DIR)report.o $(SRC_DIR)runtime.o $(SRC_DIR)set_all.o \
	$(SRC_DIR)show_eq.o $(SRC_DIR)util.o $(SRC_DIR)variab.o \
	$(SWITCH_CC_LNK) -L$(PATH_TCL_LIB) $(TCL_LIB) -L$(PATH_TK_LIB) $(TK_LIB) \
	-L$(PATH_LIB) $(LIBS) -o $(TARGET)

# compile modules
$(FUN).o: $(FUN).cpp $(FUN_EXTRA) model_options.txt \
$(SRC_DIR)check.h $(SRC_DIR)choose.h $(SRC_DIR)decl.h.gch \
$(SRC_DIR)fun_head.h $(SRC_DIR)fun_head_fast.h
	$(CC) $(GLOBAL_CC) $(SWITCH_CC) $(INCLUDE) \
	-c $(FUN).cpp -o $(FUN).o
	
$(SRC_DIR)main.o: $(SRC_DIR)main.cpp \
$(SRC_DIR)choose.h $(SRC_DIR)decl.h.gch $(SRC_DIR)system_options.txt
	$(CC) $(GLOBAL_CC) $(SSWITCH_CC) $(INCLUDE) \
	-c $(SRC_DIR)main.cpp -o $(SRC_DIR)main.o

$(SRC_DIR)lsdmain.o: $(SRC_DIR)lsdmain.cpp \
$(SRC_DIR)choose.h $(SRC_DIR)decl.h.gch $(SRC_DIR)system_options.txt
	$(CC) $(GLOBAL_CC) $(SSWITCH_CC) $(INCLUDE) \
	-c $(SRC_DIR)lsdmain.cpp -o $(SRC_DIR)lsdmain.o

$(SRC_DIR)analysis.o: $(SRC_DIR)analysis.cpp \
$(SRC_DIR)choose.h $(SRC_DIR)decl.h.gch $(SRC_DIR)system_options.txt
	$(CC) $(GLOBAL_CC) $(SSWITCH_CC) $(INCLUDE) \
	-c $(SRC_DIR)analysis.cpp -o $(SRC_DIR)analysis.o

$(SRC_DIR)debug.o: $(SRC_DIR)debug.cpp \
$(SRC_DIR)choose.h $(SRC_DIR)decl.h.gch $(SRC_DIR)system_options.txt
	$(CC) $(GLOBAL_CC) $(SSWITCH_CC) $(INCLUDE) \
	-c $(SRC_DIR)debug.cpp -o $(SRC_DIR)debug.o

$(SRC_DIR)draw.o: $(SRC_DIR)draw.cpp \
$(SRC_DIR)choose.h $(SRC_DIR)decl.h.gch $(SRC_DIR)system_options.txt
	$(CC) $(GLOBAL_CC) $(SSWITCH_CC) $(INCLUDE) \
	-c $(SRC_DIR)draw.cpp -o $(SRC_DIR)draw.o

$(SRC_DIR)edit.o: $(SRC_DIR)edit.cpp \
$(SRC_DIR)choose.h $(SRC_DIR)decl.h.gch $(SRC_DIR)system_options.txt
	$(CC) $(GLOBAL_CC) $(SSWITCH_CC) $(INCLUDE) \
	-c $(SRC_DIR)edit.cpp -o $(SRC_DIR)edit.o

$(SRC_DIR)edit_dat.o: $(SRC_DIR)edit_dat.cpp \
$(SRC_DIR)choose.h $(SRC_DIR)decl.h.gch $(SRC_DIR)system_options.txt
	$(CC) $(GLOBAL_CC) $(SSWITCH_CC) $(INCLUDE) \
	-c $(SRC_DIR)edit_dat.cpp -o $(SRC_DIR)edit_dat.o

$(SRC_DIR)file.o: $(SRC_DIR)file.cpp \
$(SRC_DIR)choose.h $(SRC_DIR)decl.h.gch $(SRC_DIR)system_options.txt
	$(CC) $(GLOBAL_CC) $(SSWITCH_CC) $(INCLUDE) \
	-c $(SRC_DIR)file.cpp -o $(SRC_DIR)file.o

$(SRC_DIR)interf.o: $(SRC_DIR)interf.cpp \
$(SRC_DIR)choose.h $(SRC_DIR)decl.h.gch $(SRC_DIR)system_options.txt
	$(CC) $(GLOBAL_CC) $(SSWITCH_CC) $(INCLUDE) \
	-c $(SRC_DIR)interf.cpp -o $(SRC_DIR)interf.o

$(SRC_DIR)nets.o: $(SRC_DIR)nets.cpp \
$(SRC_DIR)choose.h $(SRC_DIR)decl.h.gch $(SRC_DIR)system_options.txt
	$(CC) $(GLOBAL_CC) $(SSWITCH_CC) $(INCLUDE) \
	-c $(SRC_DIR)nets.cpp -o $(SRC_DIR)nets.o

$(SRC_DIR)object.o: $(SRC_DIR)object.cpp \
$(SRC_DIR)choose.h $(SRC_DIR)decl.h.gch $(SRC_DIR)system_options.txt
	$(CC) $(GLOBAL_CC) $(SSWITCH_CC) $(INCLUDE) \
	-c $(SRC_DIR)object.cpp -o $(SRC_DIR)object.o

$(SRC_DIR)report.o: $(SRC_DIR)report.cpp \
$(SRC_DIR)choose.h $(SRC_DIR)decl.h.gch $(SRC_DIR)system_options.txt
	$(CC) $(GLOBAL_CC) $(SSWITCH_CC) $(INCLUDE) \
	-c $(SRC_DIR)report.cpp -o $(SRC_DIR)report.o

$(SRC_DIR)runtime.o: $(SRC_DIR)runtime.cpp \
$(SRC_DIR)choose.h $(SRC_DIR)decl.h.gch $(SRC_DIR)system_options.txt
	$(CC) $(GLOBAL_CC) $(SSWITCH_CC) $(INCLUDE) \
	-c $(SRC_DIR)runtime.cpp -o $(SRC_DIR)runtime.o

$(SRC_DIR)set_all.o: $(SRC_DIR)set_all.cpp $(SRC_DIR)nolh.h \
$(SRC_DIR)choose.h $(SRC_DIR)decl.h.gch $(SRC_DIR)system_options.txt
	$(CC) $(GLOBAL_CC) $(SSWITCH_CC) $(INCLUDE) \
	-c $(SRC_DIR)set_all.cpp -o $(SRC_DIR)set_all.o

$(SRC_DIR)show_eq.o: $(SRC_DIR)show_eq.cpp \
$(SRC_DIR)choose.h $(SRC_DIR)decl.h.gch $(SRC_DIR)system_options.txt
	$(CC) $(GLOBAL_CC) $(SSWITCH_CC) $(INCLUDE) \
	-c $(SRC_DIR)show_eq.cpp -o $(SRC_DIR)show_eq.o

$(SRC_DIR)util.o: $(SRC_DIR)util.cpp \
$(SRC_DIR)choose.h $(SRC_DIR)decl.h.gch $(SRC_DIR)system_options.txt
	$(CC) $(GLOBAL_CC) $(SSWITCH_CC) $(INCLUDE) \
	-c $(SRC_DIR)util.cpp -o $(SRC_DIR)util.o

$(SRC_DIR)variab.o: $(SRC_DIR)variab.cpp \
$(SRC_DIR)choose.h $(SRC_DIR)decl.h.gch $(SRC_DIR)system_options.txt
	$(CC) $(GLOBAL_CC) $(SSWITCH_CC) $(INCLUDE) \
	-c $(SRC_DIR)variab.cpp -o $(SRC_DIR)variab.o

# pre-compile headers
$(SRC_DIR)decl.h.gch: $(SRC_DIR)decl.h \
$(SRC_DIR)choose.h $(SRC_DIR)system_options.txt
	$(CC) $(GLOBAL_CC) $(SSWITCH_CC) $(INCLUDE) \
	-c $(SRC_DIR)decl.h -o $(SRC_DIR)decl.h.gch

clean:
	rm $(SRC_DIR)*.o $(SRC_DIR)*.gch $(FUN).o $(TARGET)*