#!/bin/bash
# Script generated by LSD
echo "Processing 13 configuration files in up to 6 parallel processes..."
if [ "$1" = "" ]; then LSD_EXEC="/home/italo/LSD/Work/model_jeec/lsdNW"; else LSD_EXEC="$1"; fi
if [ "$2" = "" ]; then LSD_CONFIG_PATH="/home/italo/LSD/Work/model_jeec/Data_analysis/Sobol"; else LSD_CONFIG_PATH="$2"; fi
echo "LSD executable: $LSD_EXEC"
echo "Configuration path: $LSD_CONFIG_PATH"
echo "Use Sobol.sh LSD_EXEC CONFIG_PATH to change default paths"
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/Sobol_30.lsd    > "$LSD_CONFIG_PATH"/Sobol_30.log 2>&1 &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/Sobol_31.lsd    > "$LSD_CONFIG_PATH"/Sobol_31.log 2>&1 &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/Sobol_32.lsd    > "$LSD_CONFIG_PATH"/Sobol_32.log 2>&1 &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/Sobol_33.lsd    > "$LSD_CONFIG_PATH"/Sobol_33.log 2>&1 &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/Sobol_34.lsd    > "$LSD_CONFIG_PATH"/Sobol_34.log 2>&1 &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/Sobol_35.lsd    > "$LSD_CONFIG_PATH"/Sobol_35.log 2>&1 &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/Sobol_36.lsd    > "$LSD_CONFIG_PATH"/Sobol_36.log 2>&1 &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/Sobol_37.lsd    > "$LSD_CONFIG_PATH"/Sobol_37.log 2>&1 &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/Sobol_38.lsd    > "$LSD_CONFIG_PATH"/Sobol_38.log 2>&1 &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/Sobol_39.lsd    > "$LSD_CONFIG_PATH"/Sobol_39.log 2>&1 &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/Sobol_73.lsd    > "$LSD_CONFIG_PATH"/Sobol_73.log 2>&1 &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/Sobol_74.lsd    > "$LSD_CONFIG_PATH"/Sobol_74.log 2>&1 &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/Sobol_75.lsd    > "$LSD_CONFIG_PATH"/Sobol_75.log 2>&1 &
echo "13 log files being generated."
