#!/bin/bash
# Script generated by LSD
echo "Processing 75 configuration files in up to 6 parallel processes..."
if [ "$1" = "" ]; then LSD_EXEC="/home/italo/LSD/Work/model_jeec/lsdNW"; else LSD_EXEC="$1"; fi
if [ "$2" = "" ]; then LSD_CONFIG_PATH="/home/italo/LSD/Work/model_jeec/Data_analysis/Sobol"; else LSD_CONFIG_PATH="$2"; fi
echo "LSD executable: $LSD_EXEC"
echo "Configuration path: $LSD_CONFIG_PATH"
echo "Use Sobol.sh LSD_EXEC CONFIG_PATH to change default paths"
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/Sobol -s 1 -e 13    > "$LSD_CONFIG_PATH"/Sobol_1.log 2>&1 &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/Sobol -s 14 -e 26    > "$LSD_CONFIG_PATH"/Sobol_2.log 2>&1 &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/Sobol -s 27 -e 39    > "$LSD_CONFIG_PATH"/Sobol_3.log 2>&1 &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/Sobol -s 40 -e 51    > "$LSD_CONFIG_PATH"/Sobol_4.log 2>&1 &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/Sobol -s 52 -e 63    > "$LSD_CONFIG_PATH"/Sobol_5.log 2>&1 &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/Sobol -s 64 -e 75    > "$LSD_CONFIG_PATH"/Sobol_6.log 2>&1 &
echo "6 log files being generated: Sobol_1.log to Sobol_6.log ."
