#!/bin/bash
# Script generated by LSD
echo "Processing 100 configuration files in up to 32 parallel processes..."
if [ "$1" = "" ]; then LSD_EXEC="nice /home/gpetrini/LSD/Work/PhD/mkks_irf/lsdNW"; else LSD_EXEC="$1"; fi
if [ "$2" = "" ]; then LSD_CONFIG_PATH="/home/gpetrini/LSD/Work/PhD/mkks_irf/data-irf/S3-noshock"; else LSD_CONFIG_PATH="$2"; fi
echo "LSD executable: $LSD_EXEC"
echo "Configuration path: $LSD_CONFIG_PATH"
echo "Use S3-noshock.sh LSD_EXEC CONFIG_PATH to change default paths"
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/S3-noshock -s 1 -e 4 -p -l "$LSD_CONFIG_PATH"/S3-noshock_1.log &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/S3-noshock -s 5 -e 8 -p -l "$LSD_CONFIG_PATH"/S3-noshock_2.log &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/S3-noshock -s 9 -e 12 -p -l "$LSD_CONFIG_PATH"/S3-noshock_3.log &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/S3-noshock -s 13 -e 16 -p -l "$LSD_CONFIG_PATH"/S3-noshock_4.log &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/S3-noshock -s 17 -e 19 -p -l "$LSD_CONFIG_PATH"/S3-noshock_5.log &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/S3-noshock -s 20 -e 22 -p -l "$LSD_CONFIG_PATH"/S3-noshock_6.log &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/S3-noshock -s 23 -e 25 -p -l "$LSD_CONFIG_PATH"/S3-noshock_7.log &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/S3-noshock -s 26 -e 28 -p -l "$LSD_CONFIG_PATH"/S3-noshock_8.log &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/S3-noshock -s 29 -e 31 -p -l "$LSD_CONFIG_PATH"/S3-noshock_9.log &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/S3-noshock -s 32 -e 34 -p -l "$LSD_CONFIG_PATH"/S3-noshock_10.log &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/S3-noshock -s 35 -e 37 -p -l "$LSD_CONFIG_PATH"/S3-noshock_11.log &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/S3-noshock -s 38 -e 40 -p -l "$LSD_CONFIG_PATH"/S3-noshock_12.log &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/S3-noshock -s 41 -e 43 -p -l "$LSD_CONFIG_PATH"/S3-noshock_13.log &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/S3-noshock -s 44 -e 46 -p -l "$LSD_CONFIG_PATH"/S3-noshock_14.log &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/S3-noshock -s 47 -e 49 -p -l "$LSD_CONFIG_PATH"/S3-noshock_15.log &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/S3-noshock -s 50 -e 52 -p -l "$LSD_CONFIG_PATH"/S3-noshock_16.log &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/S3-noshock -s 53 -e 55 -p -l "$LSD_CONFIG_PATH"/S3-noshock_17.log &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/S3-noshock -s 56 -e 58 -p -l "$LSD_CONFIG_PATH"/S3-noshock_18.log &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/S3-noshock -s 59 -e 61 -p -l "$LSD_CONFIG_PATH"/S3-noshock_19.log &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/S3-noshock -s 62 -e 64 -p -l "$LSD_CONFIG_PATH"/S3-noshock_20.log &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/S3-noshock -s 65 -e 67 -p -l "$LSD_CONFIG_PATH"/S3-noshock_21.log &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/S3-noshock -s 68 -e 70 -p -l "$LSD_CONFIG_PATH"/S3-noshock_22.log &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/S3-noshock -s 71 -e 73 -p -l "$LSD_CONFIG_PATH"/S3-noshock_23.log &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/S3-noshock -s 74 -e 76 -p -l "$LSD_CONFIG_PATH"/S3-noshock_24.log &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/S3-noshock -s 77 -e 79 -p -l "$LSD_CONFIG_PATH"/S3-noshock_25.log &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/S3-noshock -s 80 -e 82 -p -l "$LSD_CONFIG_PATH"/S3-noshock_26.log &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/S3-noshock -s 83 -e 85 -p -l "$LSD_CONFIG_PATH"/S3-noshock_27.log &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/S3-noshock -s 86 -e 88 -p -l "$LSD_CONFIG_PATH"/S3-noshock_28.log &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/S3-noshock -s 89 -e 91 -p -l "$LSD_CONFIG_PATH"/S3-noshock_29.log &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/S3-noshock -s 92 -e 94 -p -l "$LSD_CONFIG_PATH"/S3-noshock_30.log &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/S3-noshock -s 95 -e 97 -p -l "$LSD_CONFIG_PATH"/S3-noshock_31.log &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/S3-noshock -s 98 -e 100 -p -l "$LSD_CONFIG_PATH"/S3-noshock_32.log &
echo "32 log files being generated: S3-noshock_1.log to S3-noshock_32.log ."
