#!/bin/bash
# Script generated by LSD
echo "Processing 3 configuration files in up to 8 parallel processes..."
if [ "$1" = "" ]; then LSD_EXEC="/home/italo/LSD/Work/model_jeec/lsdNW"; else LSD_EXEC="$1"; fi
if [ "$2" = "" ]; then LSD_CONFIG_PATH="/home/italo/LSD/Work/model_jeec/Data_analysis/Base_scen"; else LSD_CONFIG_PATH="$2"; fi
echo "LSD executable: $LSD_EXEC"
echo "Configuration path: $LSD_CONFIG_PATH"
echo "Use S1.sh LSD_EXEC CONFIG_PATH to change default paths"
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/S1.lsd    > "$LSD_CONFIG_PATH"/S1.log 2>&1 &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/S2.lsd    > "$LSD_CONFIG_PATH"/S2.log 2>&1 &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/S3.lsd    > "$LSD_CONFIG_PATH"/S3.log 2>&1 &
echo "3 log files being generated."
