#!/bin/bash
# Script generated by LSD
echo "Processing 100 configuration files in up to 32 parallel processes..."
if [ "$1" = "" ]; then LSD_EXEC="nice /home/gpetrini/LSD/Work/PhD/mkks_irf/lsdNW"; else LSD_EXEC="$1"; fi
if [ "$2" = "" ]; then LSD_CONFIG_PATH="/home/gpetrini/LSD/Work/PhD/mkks_irf/data-irf/S1-shock"; else LSD_CONFIG_PATH="$2"; fi
echo "LSD executable: $LSD_EXEC"
echo "Configuration path: $LSD_CONFIG_PATH"
echo "Use S1-shock.sh LSD_EXEC CONFIG_PATH to change default paths"
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/S1-shock -s 1 -e 4 -p -l "$LSD_CONFIG_PATH"/S1-shock_1.log &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/S1-shock -s 5 -e 8 -p -l "$LSD_CONFIG_PATH"/S1-shock_2.log &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/S1-shock -s 9 -e 12 -p -l "$LSD_CONFIG_PATH"/S1-shock_3.log &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/S1-shock -s 13 -e 16 -p -l "$LSD_CONFIG_PATH"/S1-shock_4.log &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/S1-shock -s 17 -e 19 -p -l "$LSD_CONFIG_PATH"/S1-shock_5.log &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/S1-shock -s 20 -e 22 -p -l "$LSD_CONFIG_PATH"/S1-shock_6.log &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/S1-shock -s 23 -e 25 -p -l "$LSD_CONFIG_PATH"/S1-shock_7.log &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/S1-shock -s 26 -e 28 -p -l "$LSD_CONFIG_PATH"/S1-shock_8.log &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/S1-shock -s 29 -e 31 -p -l "$LSD_CONFIG_PATH"/S1-shock_9.log &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/S1-shock -s 32 -e 34 -p -l "$LSD_CONFIG_PATH"/S1-shock_10.log &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/S1-shock -s 35 -e 37 -p -l "$LSD_CONFIG_PATH"/S1-shock_11.log &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/S1-shock -s 38 -e 40 -p -l "$LSD_CONFIG_PATH"/S1-shock_12.log &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/S1-shock -s 41 -e 43 -p -l "$LSD_CONFIG_PATH"/S1-shock_13.log &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/S1-shock -s 44 -e 46 -p -l "$LSD_CONFIG_PATH"/S1-shock_14.log &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/S1-shock -s 47 -e 49 -p -l "$LSD_CONFIG_PATH"/S1-shock_15.log &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/S1-shock -s 50 -e 52 -p -l "$LSD_CONFIG_PATH"/S1-shock_16.log &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/S1-shock -s 53 -e 55 -p -l "$LSD_CONFIG_PATH"/S1-shock_17.log &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/S1-shock -s 56 -e 58 -p -l "$LSD_CONFIG_PATH"/S1-shock_18.log &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/S1-shock -s 59 -e 61 -p -l "$LSD_CONFIG_PATH"/S1-shock_19.log &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/S1-shock -s 62 -e 64 -p -l "$LSD_CONFIG_PATH"/S1-shock_20.log &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/S1-shock -s 65 -e 67 -p -l "$LSD_CONFIG_PATH"/S1-shock_21.log &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/S1-shock -s 68 -e 70 -p -l "$LSD_CONFIG_PATH"/S1-shock_22.log &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/S1-shock -s 71 -e 73 -p -l "$LSD_CONFIG_PATH"/S1-shock_23.log &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/S1-shock -s 74 -e 76 -p -l "$LSD_CONFIG_PATH"/S1-shock_24.log &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/S1-shock -s 77 -e 79 -p -l "$LSD_CONFIG_PATH"/S1-shock_25.log &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/S1-shock -s 80 -e 82 -p -l "$LSD_CONFIG_PATH"/S1-shock_26.log &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/S1-shock -s 83 -e 85 -p -l "$LSD_CONFIG_PATH"/S1-shock_27.log &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/S1-shock -s 86 -e 88 -p -l "$LSD_CONFIG_PATH"/S1-shock_28.log &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/S1-shock -s 89 -e 91 -p -l "$LSD_CONFIG_PATH"/S1-shock_29.log &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/S1-shock -s 92 -e 94 -p -l "$LSD_CONFIG_PATH"/S1-shock_30.log &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/S1-shock -s 95 -e 97 -p -l "$LSD_CONFIG_PATH"/S1-shock_31.log &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/S1-shock -s 98 -e 100 -p -l "$LSD_CONFIG_PATH"/S1-shock_32.log &
echo "32 log files being generated: S1-shock_1.log to S1-shock_32.log ."
