#!/bin/bash
# Script generated by LSD
echo "Processing 600 configuration files in up to 32 parallel processes..."
if [ "$1" = "" ]; then LSD_EXEC="nice /home/gpetrini/LSD/Work/PhD/mkks_irf/lsdNW"; else LSD_EXEC="$1"; fi
if [ "$2" = "" ]; then LSD_CONFIG_PATH="/home/gpetrini/LSD/Work/PhD/mkks_irf/data-irf/S1-shock"; else LSD_CONFIG_PATH="$2"; fi
echo "LSD executable: $LSD_EXEC"
echo "Configuration path: $LSD_CONFIG_PATH"
echo "Use S1-shock.sh LSD_EXEC CONFIG_PATH to change default paths"
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/S1-shock -s 1 -e 19 -p -l "$LSD_CONFIG_PATH"/S1-shock_1.log &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/S1-shock -s 20 -e 38 -p -l "$LSD_CONFIG_PATH"/S1-shock_2.log &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/S1-shock -s 39 -e 57 -p -l "$LSD_CONFIG_PATH"/S1-shock_3.log &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/S1-shock -s 58 -e 76 -p -l "$LSD_CONFIG_PATH"/S1-shock_4.log &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/S1-shock -s 77 -e 95 -p -l "$LSD_CONFIG_PATH"/S1-shock_5.log &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/S1-shock -s 96 -e 114 -p -l "$LSD_CONFIG_PATH"/S1-shock_6.log &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/S1-shock -s 115 -e 133 -p -l "$LSD_CONFIG_PATH"/S1-shock_7.log &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/S1-shock -s 134 -e 152 -p -l "$LSD_CONFIG_PATH"/S1-shock_8.log &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/S1-shock -s 153 -e 171 -p -l "$LSD_CONFIG_PATH"/S1-shock_9.log &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/S1-shock -s 172 -e 190 -p -l "$LSD_CONFIG_PATH"/S1-shock_10.log &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/S1-shock -s 191 -e 209 -p -l "$LSD_CONFIG_PATH"/S1-shock_11.log &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/S1-shock -s 210 -e 228 -p -l "$LSD_CONFIG_PATH"/S1-shock_12.log &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/S1-shock -s 229 -e 247 -p -l "$LSD_CONFIG_PATH"/S1-shock_13.log &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/S1-shock -s 248 -e 266 -p -l "$LSD_CONFIG_PATH"/S1-shock_14.log &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/S1-shock -s 267 -e 285 -p -l "$LSD_CONFIG_PATH"/S1-shock_15.log &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/S1-shock -s 286 -e 304 -p -l "$LSD_CONFIG_PATH"/S1-shock_16.log &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/S1-shock -s 305 -e 323 -p -l "$LSD_CONFIG_PATH"/S1-shock_17.log &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/S1-shock -s 324 -e 342 -p -l "$LSD_CONFIG_PATH"/S1-shock_18.log &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/S1-shock -s 343 -e 361 -p -l "$LSD_CONFIG_PATH"/S1-shock_19.log &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/S1-shock -s 362 -e 380 -p -l "$LSD_CONFIG_PATH"/S1-shock_20.log &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/S1-shock -s 381 -e 399 -p -l "$LSD_CONFIG_PATH"/S1-shock_21.log &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/S1-shock -s 400 -e 418 -p -l "$LSD_CONFIG_PATH"/S1-shock_22.log &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/S1-shock -s 419 -e 437 -p -l "$LSD_CONFIG_PATH"/S1-shock_23.log &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/S1-shock -s 438 -e 456 -p -l "$LSD_CONFIG_PATH"/S1-shock_24.log &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/S1-shock -s 457 -e 474 -p -l "$LSD_CONFIG_PATH"/S1-shock_25.log &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/S1-shock -s 475 -e 492 -p -l "$LSD_CONFIG_PATH"/S1-shock_26.log &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/S1-shock -s 493 -e 510 -p -l "$LSD_CONFIG_PATH"/S1-shock_27.log &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/S1-shock -s 511 -e 528 -p -l "$LSD_CONFIG_PATH"/S1-shock_28.log &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/S1-shock -s 529 -e 546 -p -l "$LSD_CONFIG_PATH"/S1-shock_29.log &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/S1-shock -s 547 -e 564 -p -l "$LSD_CONFIG_PATH"/S1-shock_30.log &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/S1-shock -s 565 -e 582 -p -l "$LSD_CONFIG_PATH"/S1-shock_31.log &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/S1-shock -s 583 -e 600 -p -l "$LSD_CONFIG_PATH"/S1-shock_32.log &
echo "32 log files being generated: S1-shock_1.log to S1-shock_32.log ."
