#!/bin/bash
# Script generated by LSD
echo "Processing 65 configuration files in up to 8 parallel processes..."
if [ "$1" = "" ]; then LSD_EXEC="/home/italo/LSD/Work/model_jeec/lsdNW"; else LSD_EXEC="$1"; fi
if [ "$2" = "" ]; then LSD_CONFIG_PATH="/home/italo/LSD/Work/model_jeec/Data_analysis/Sobol"; else LSD_CONFIG_PATH="$2"; fi
echo "LSD executable: $LSD_EXEC"
echo "Configuration path: $LSD_CONFIG_PATH"
echo "Use Sobol.sh LSD_EXEC CONFIG_PATH to change default paths"
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/Sobol -s 1 -e 9    > "$LSD_CONFIG_PATH"/Sobol_1.log 2>&1 &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/Sobol -s 10 -e 17    > "$LSD_CONFIG_PATH"/Sobol_2.log 2>&1 &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/Sobol -s 18 -e 25    > "$LSD_CONFIG_PATH"/Sobol_3.log 2>&1 &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/Sobol -s 26 -e 33    > "$LSD_CONFIG_PATH"/Sobol_4.log 2>&1 &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/Sobol -s 34 -e 41    > "$LSD_CONFIG_PATH"/Sobol_5.log 2>&1 &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/Sobol -s 42 -e 49    > "$LSD_CONFIG_PATH"/Sobol_6.log 2>&1 &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/Sobol -s 50 -e 57    > "$LSD_CONFIG_PATH"/Sobol_7.log 2>&1 &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/Sobol -s 58 -e 65    > "$LSD_CONFIG_PATH"/Sobol_8.log 2>&1 &
echo "8 log files being generated: Sobol_1.log to Sobol_8.log ."
